/**
 * Service worker — the thing that makes QG1 true (CLAUDE.md §1.1, TD4).
 *
 * The app must launch from a cold start in airplane mode. That means the app
 * shell *and* the PGlite runtime are precached at install time; nothing on the
 * offline path is ever fetched lazily.
 *
 * Both lists are read from JSON at install rather than hard-coded here:
 * `app-shell.json` is checked against the filesystem by a test, and
 * `vendor/pglite/assets.json` is generated by `npm run vendor`. A hard-coded
 * list would rot silently, and a rotted list means a golfer standing on the
 * first tee with a broken app.
 */

/// <reference lib="webworker" />

/**
 * `self` is typed as a Window because the project's lib includes DOM. Narrow it
 * once here rather than casting at every call site.
 *
 * @type {ServiceWorkerGlobalScope}
 */
const worker = /** @type {any} */ (self);

const CACHE_NAME = 'golftrainer-v1';

/**
 * @param {string} url
 * @returns {Promise<string[]>}
 */
async function readUrlList(url) {
  const response = await fetch(url, { cache: 'no-cache' });
  if (!response.ok) {
    throw new Error(`Precache manifest ${url} is unavailable (HTTP ${response.status}).`);
  }
  const body = await response.json();
  return body.shell ?? body.assets ?? [];
}

async function precache() {
  const [shell, pglite] = await Promise.all([
    readUrlList('/app-shell.json'),
    readUrlList('/vendor/pglite/assets.json'),
  ]);

  const cache = await caches.open(CACHE_NAME);

  // addAll is atomic: one missing file fails the whole install, which is what
  // we want. A partially cached shell is worse than an obvious failure — it
  // would look installed and then break on the course.
  await cache.addAll([...shell, ...pglite]);
}

worker.addEventListener('install', (event) => {
  event.waitUntil(precache().then(() => worker.skipWaiting()));
});

worker.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names.filter((name) => name !== CACHE_NAME).map((name) => caches.delete(name)),
      );
      await worker.clients.claim();
    })(),
  );
});

/**
 * Cache-first for everything precached. The offline core never depends on a
 * network response, so there is no "try network, fall back" dance here — that
 * pattern would make cold starts on the course depend on a timeout.
 */
worker.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  event.respondWith(
    (async () => {
      const cached = await caches.match(request, { ignoreSearch: true });
      if (cached) return cached;

      try {
        return await fetch(request);
      } catch {
        // Navigations must still resolve offline, even for an unknown path.
        if (request.mode === 'navigate') {
          const shell = await caches.match('/index.html');
          if (shell) return shell;
        }
        throw new Error(`Offline and ${request.url} is not precached.`);
      }
    })(),
  );
});
