/**
 * Service worker — the thing that makes QG1 true (CLAUDE.md §1.1, TD4).
 *
 * The app must launch from a cold start in airplane mode. That means the app
 * shell *and* the PGlite runtime are precached at install time; nothing on the
 * offline path is ever fetched lazily.
 *
 * Both lists are read from JSON at install rather than hard-coded here:
 * `app-shell.json` is checked against the filesystem by a test, and
 * `vendor/pglite/assets.json` is generated by `npm run vendor`. A hard-coded
 * list would rot silently, and a rotted list means a golfer standing on the
 * first tee with a broken app.
 */

/// <reference lib="webworker" />

/**
 * `self` is typed as a Window because the project's lib includes DOM. Narrow it
 * once here rather than casting at every call site.
 *
 * @type {ServiceWorkerGlobalScope}
 */
const worker = /** @type {any} */ (self);

const CACHE_NAME = 'golftrainer-v1';

/**
 * Where the app is mounted — `https://host/` locally, `https://host/golftrainer/`
 * on GitHub Pages. Derived from the worker's own URL, so nothing here needs to
 * know the deployment path, and both manifests can hold relative entries.
 */
const BASE = new URL('./', worker.location.href);

/**
 * @param {string} relativeUrl
 * @returns {Promise<string[]>} entries resolved against BASE
 */
async function readUrlList(relativeUrl) {
  const url = new URL(relativeUrl, BASE).href;
  const response = await fetch(url, { cache: 'no-cache' });
  if (!response.ok) {
    throw new Error(`Precache manifest ${url} is unavailable (HTTP ${response.status}).`);
  }
  const body = await response.json();
  const entries = body.shell ?? body.assets ?? [];
  return entries.map((/** @type {string} */ entry) => new URL(entry, BASE).href);
}

/**
 * The manifests themselves. Cached alongside what they list, so that
 * reinstalling the worker with no network still finds them — a manifest that
 * is only reachable online would make a cold reinstall on the course fail.
 * `app-shell.json` also appears in its own shell list; the cache dedupes.
 */
const MANIFESTS = ['app-shell.json', 'vendor/pglite/assets.json'];

async function precache() {
  const listed = await Promise.all(MANIFESTS.map((name) => readUrlList(name)));
  const manifests = MANIFESTS.map((name) => new URL(name, BASE).href);

  const cache = await caches.open(CACHE_NAME);

  // addAll is atomic: one missing file fails the whole install, which is what
  // we want. A partially cached shell is worse than an obvious failure — it
  // would look installed and then break on the course.
  await cache.addAll([...new Set([...manifests, ...listed.flat()])]);
}

worker.addEventListener('install', (event) => {
  event.waitUntil(precache().then(() => worker.skipWaiting()));
});

worker.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names.filter((name) => name !== CACHE_NAME).map((name) => caches.delete(name)),
      );
      await worker.clients.claim();
    })(),
  );
});

/**
 * Cache-first for everything precached. The offline core never depends on a
 * network response, so there is no "try network, fall back" dance here — that
 * pattern would make cold starts on the course depend on a timeout.
 */
worker.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  event.respondWith(
    (async () => {
      const cached = await caches.match(request, { ignoreSearch: true });
      if (cached) return cached;

      try {
        return await fetch(request);
      } catch {
        // Navigations must still resolve offline, even for an unknown path.
        if (request.mode === 'navigate') {
          const shell = await caches.match(new URL('index.html', BASE).href);
          if (shell) return shell;
        }
        throw new Error(`Offline and ${request.url} is not precached.`);
      }
    })(),
  );
});
