/**
 * Copies Leaflet out of node_modules into `vendor/leaflet/` (TD7).
 *
 * Same reasoning as PGlite (TD9) with one difference worth being clear about:
 * PGlite is vendored because a CDN fetch on the offline critical path would
 * breach the dependency rule. Leaflet is not on that path at all — it is only
 * ever loaded by the online screens. It is vendored for consistency and to keep
 * the runtime surface served from one origin, not because QG1 demands it.
 *
 * Which is why `assets.json` here is deliberately *not* a precache list. These
 * files are deployed and never precached: putting a map library into the shell
 * the golfer carries onto the course would cost megabytes for a screen that
 * refuses to open without a network.
 */

import { copyFile, mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';

const require = createRequire(import.meta.url);
const repoRoot = path.resolve(import.meta.dirname, '..');

const leafletRoot = path.dirname(require.resolve('leaflet/package.json'));
const sourceDir = path.join(leafletRoot, 'dist');
const targetDir = path.join(repoRoot, 'vendor', 'leaflet');
const publicPrefix = 'vendor/leaflet';

/**
 * The ES module build, its stylesheet, and the marker images the stylesheet
 * refers to. Not the UMD build, not the sourcemaps: the app is ES modules
 * (TD2), and 400 KB of sourcemap helps nobody on a phone.
 */
const files = [
  'leaflet-src.esm.js',
  'leaflet.css',
  'images/marker-icon.png',
  'images/marker-icon-2x.png',
  'images/marker-shadow.png',
  'images/layers.png',
  'images/layers-2x.png',
];

/**
 * A declaration file, written here rather than copied.
 *
 * Leaflet ships no `.d.ts` (they live in the separate `@types/leaflet`), so
 * without this `tsc` follows the import and type-checks Leaflet's own source,
 * reporting a few hundred of its errors as ours. PGlite solved the same problem
 * by shipping declarations next to the bundle; this reproduces that.
 *
 * Deliberately loose. The point is to stop tsc reading the implementation, not
 * to model Leaflet's API — `map-view.js` is the only file that touches it and
 * it treats the library as untyped on purpose (TD7: a thin, swappable seam).
 */
const DECLARATION = `// Generated by tools/vendor-leaflet.mjs. Not Leaflet's own typings.
export const map: any;
export const tileLayer: any;
export const marker: any;
export const circleMarker: any;
export const polyline: any;
export const layerGroup: any;
export const latLng: any;
export const latLngBounds: any;
export const icon: any;
export const control: any;
declare const leaflet: any;
export default leaflet;
`;

async function main() {
  const manifest = JSON.parse(await readFile(path.join(leafletRoot, 'package.json'), 'utf8'));

  await rm(targetDir, { recursive: true, force: true });
  await mkdir(path.join(targetDir, 'images'), { recursive: true });

  let bytes = 0;
  for (const relative of files) {
    const source = path.join(sourceDir, relative);
    const target = path.join(targetDir, relative);
    await copyFile(source, target);
    bytes += (await stat(target)).size;
  }

  // Never served and never listed in assets.json: tsc resolves it beside the
  // bundle and skips the JavaScript entirely.
  await writeFile(path.join(targetDir, 'leaflet-src.esm.d.ts'), DECLARATION, 'utf8');

  await writeFile(
    path.join(targetDir, 'assets.json'),
    `${JSON.stringify(
      {
        version: manifest.version,
        license: manifest.license,
        precache: false,
        assets: files.map((name) => `${publicPrefix}/${name}`),
      },
      null,
      2,
    )}\n`,
    'utf8',
  );

  const kilobytes = (bytes / 1024).toFixed(0);
  console.log(`Vendored Leaflet ${manifest.version}: ${files.length} files, ${kilobytes} KB.`);
}

await main();
